version: '3'

services:
  web:
    image: "developerchoims/hoopitest"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    container_name: hoopi