spring:
  application:
    name: hoopi

  datasource:
    url: ${RDS_HOST}
    username: ${RDS_NM}
    password: ${RDS_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000


  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      host: ${REDIS_HOST}
      port: 15250
      password: ${RDS_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PWD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
sms:
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
  api_phone: ${API_PHONE}

jwt:
  key: ${JWT_KEY}


logging:
  level:
    org:
      springframework:
        web: DEBUG